# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.box = "bento/centos-7.5"
 config.vm.define "server1" do |server1|
   server1.vm.hostname = "server1"
   server1.vm.network "private_network", ip: "192.168.0.10"
   server1.vm.provision "shell", inline: <<-SHELL
     cat /etc/hosts|grep server2|| echo 192.168.0.11 server2 >>/etc/hosts
    SHELL
 end

 config.vm.define "server2" do |server2|
   server2.vm.hostname = "server2"
   server2.vm.network "private_network", ip: "192.168.0.11"
   server2.vm.provision "shell",path:"server2/init_p.sh",privileged: true
   server2.vm.provision "shell",path:"server2/init.sh",privileged: false
 end

end
