# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "192.168.0.10"
    server1.vm.provision "shell", inline: <<-SHELL
      cat /etc/hosts|grep server2|| echo 192.168.0.11 server2 >>/etc/hosts
    SHELL
  end
  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "192.168.0.11"
    server2.vm.provision "shell",path:"server2/init_p.sh",privileged: true
    server2.vm.provision "shell",path:"server2/init.sh",privileged: false
  end
end
