name 'docker'
maintainer 'rd-epam'
maintainer_email 'vadzim_kavaleuski@epam.com'
license 'nobody'
description 'Installs/Configures docker'
long_description 'Installs/Configures docker'
version '0.1.3'
chef_version '>= 13.0'
depends 'yumupdate'