# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#RUN bin/elasticsearch-plugin install x-pack

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
