version: "3"
services:
#  arg:  
#    version: "1.0.34"
  task7ext:
    image: localhost:5000/gradlesample/tomcat:${version}
    build:
       context: "."
       dockerfile: collectd.Dockerfile
       args:
         version: "1.0.34"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet: