version: '3'

services:
  tomcat1:
    image: localhost:5000/gradlesample/tomcat:1.0.34
    hostname:tomacat1
    networks:
      - testnet
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - 'node.role==worker'
  tomcat2:
    image: localhost:5000/gradlesample/tomcat:1.0.34
    hostname:tomacat2
    networks:
      - testnet
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - 'node.role==worker'
  htppd:
    image: localhost:5000/gradlesample/httpd:1.0.34
    networks:
      - testnet
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - 'node.role==worker'

networks:
  testnet:
    external: true