version: "3"
services:
  tomcat:
    image: localhost:5000/gradlesample/tomcat:${TAG}
    deploy:
      replicas: 2
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet: