version: "3"
services:
  task7ext:
    image: localhost:5000/gradlesample/tomcat:${TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet: