node {
  stage('Clone sources') {
    git url: 'https://github.com/VadzimKavaleuski/homeworks_Kavaleuski.git'
    sh 'git checkout task6'
  }
  stage('build') {
    sh 'chmod +rwx ./module4/gradleSample'
    dir("module4/gradleSample"){
      sh 'chmod +x ./gradlew'
      sh './gradlew clean iV build'
    }
  }
  def version="unknown"
  stage('public artifact'){
    version = sh (
      script: "cat module4/gradleSample/gradle.properties | grep \"version=\" | awk -F \"=\" '{print \$2}'",
      returnStdout: true
    ).trim()
    withCredentials([string(credentialsId: 'cfd264f7-2a2f-40d7-bf13-5febf5ba7b69', variable: 'TOKEN')]) {
      sh 'curl -X PUT -u $TOKEN -T ./module4/gradleSample/build/libs/app.war "http://localhost:8081/nexus/content/repositories/internalSample/snapshots/test/'+version+'/app.war"' 
    }   
  }
  stage('public to tomcat1'){
    httpRequest "http://192.168.0.10/status?cmd=update&from=list&w=lb&sw=server0&vwa=2"
    sshagent(['server0']) {
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.11  "sudo systemctl stop tomcat"'
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.11  "ls /var/lib/tomcat/webapps|grep app.war 2>/dev/null&&sudo rm /var/lib/tomcat/webapps/app.war 2>/dev/null"'
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.11  "ls /var/lib/tomcat/webapps|grep app 2>/dev/null&&sudo rm -r /var/lib/tomcat/webapps/app 2>/dev/null"'
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.11  "sudo curl -o \"/var/lib/tomcat/webapps/app.war\" \"http://192.168.0.100:8081/nexus/content/repositories/internalSample/snapshots/test/'+version+'/app.war\""'
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.11  "sudo systemctl start tomcat"'
      sleep 8
    }
    sh 'curl "http://192.168.0.11:8080/app/index.jsp" 2>/dev/null | grep "'+version+'" >/dev/null || exit' 
    httpRequest "http://192.168.0.10/status?cmd=update&from=list&w=lb&sw=server0&vwa=0"
  }
  stage('public to tomcat2'){
    httpRequest "http://192.168.0.10/status?cmd=update&from=list&w=lb&sw=server1&vwa=2"
    sshagent(['ba9ddb2a-38a0-4ca5-8ae7-dde5d3ab28be']) {
      sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.12  "curl -o \"/home/vagrant/app.war\" \"http://192.168.0.100:8081/nexus/content/repositories/internalSample/snapshots/test/'+version+'/app.war\""'
      withCredentials([string(credentialsId: 'tomcatsAdminCred', variable: 'tomcatsAdminCred')]) {
        sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.12  "curl \"http://$tomcatsAdminCred@localhost:8080/manager/text/undeploy?path=/app\" 2>/dev/null"'
        sh 'ssh -o StrictHostKeyChecking=no -l vagrant 192.168.0.12  "curl -X PUT -T \"/home/vagrant/app.war\" \"http://$tomcatsAdminCred@localhost:8080/manager/text/deploy?path=/app\" 2>/dev/null"'
      }      
    }
    sh 'curl "http://192.168.0.12:8080/app/index.jsp" 2>/dev/null | grep "'+version+'" >/dev/null || exit' 
    httpRequest "http://192.168.0.10/status?cmd=update&from=list&w=lb&sw=server1&vwa=0"
  }
  stage('push git'){
    sh 'git config user.email "vadzim_kavaleuski@epam.com"'
    sh 'git config user.name "jenkins job"'
    sh 'git add module4/gradleSample/gradle.properties'
    sh 'git commit -m "increase version by jenkins job"'
    sh 'git pull origin task6'
    withCredentials([string(credentialsId: 'github', variable: 'TOKEN')]) {
     sh("git push --set-upstream https://$TOKEN@github.com/VadzimKavaleuski/homeworks_Kavaleuski.git task6")
    }   
    sh 'git checkout master'
    sh 'git merge --ff task6 -m "merge task6 to master"'
    sh 'git tag -a "v'+version+'" -m "version '+version+'"'
    sh 'git pull origin master '
    withCredentials([string(credentialsId: 'github', variable: 'TOKEN')]) {
     sh("git push --set-upstream https://$TOKEN@github.com/VadzimKavaleuski/homeworks_Kavaleuski.git")
     sh("git push --tag --set-upstream https://$TOKEN@github.com/VadzimKavaleuski/homeworks_Kavaleuski.git")
    }   
  }
  //clear workspace
  deleteDir()
}