name 'docker-registry'
maintainer 'rd-epam'
maintainer_email 'vadzim_kavaleuski@epam.com'
license 'nobody'
description 'Installs/Configures docker registry'
long_description 'Installs/Configures docker registry'
version '0.1.3'
chef_version '>= 13.0'
depends 'docker'